### Get Orders
GET http://localhost:4004/manage-orders/SalesOrders HTTP/1.1


### Create Order
POST http://localhost:4004/manage-orders/SalesOrders HTTP/1.1
Content-type: application/json

{
"Email":"matmiranda@live.com.ar",
"FirstName":"Matias",
"LastName":"Miranda",
"Country": {
    "code": "AR"
    }
}

### Update Order
PUT http://localhost:4004/manage-orders/SalesOrders(ID=4b107c38-e44f-48b0-ab75-b28b38aba8f4) HTTP/1.1
Content-type: application/json

{
"Email": "danny_093@gmail.com",
"FirstName":"Daniela",
"LastName":"Santamaría",
"Country": {
    "code": "CO"
    },
"DeliveryDate": "2022-12-23T00:00:00Z",
"OrderStatus": 3
}

### Delete Order
DELETE http://localhost:4004/manage-orders/SalesOrders(ID=4b107c38-e44f-48b0-ab75-b28b38aba8f4)
